### ISSUE TITLE
[LS] Convert code to include static types

### ISSUE THREAD

**Issue by bluesign** [onflow/cadence-tools#71]
### Issue To Be Solved

Not sure where this lands, but something like this would be nice

if I have code like below:
```
var a = "deniz"
```

some tool converting this to:
```
var a : String = "deniz"
```

Extension is showing types, but also would nice to people use this somehow, then we have this on deployed contracts.

**Comment by turbolent** [comment]
I saw this feature in the Swift VS Code extension and in the Rust extension (really, rust-analyzer): It shows inferred types as inlay hints, which we already have, but also provides an action to insert the inlay hint text into the code. See e.g https://stackoverflow.com/questions/72276850/can-vs-code-rust-analyzer-insert-inlay-hints-into-the-code. 

We can probably just copy that implementation approach.

**Comment by turbolent** [comment]
Turns out this is actually a feature of VS Code: When the inlay hint provided by the language server provides text edits, then the action becomes available: https://github.com/microsoft/vscode/blob/adbcbfa5d06a268f338c00ecb15e7860261e5b63/src/vs/editor/contrib/inlayHints/browser/inlayHintsHover.ts#L97-L99
