### ISSUE TITLE
[LS] Improve auto completion for nested contexts

### ISSUE THREAD

**Issue by bluesign** [onflow/cadence-tools#92]
**Is your feature request related to a problem? Please describe.**
Auto completion does not work for nested contexts, for example:

<img width="624" alt="image" src="https://user-images.githubusercontent.com/1119338/229794428-bb97db7d-428c-42cf-9e6f-0024db5afca5.png">

**Describe the solution you'd like**

Autocompletion should work and show properties and functions for account (`acc`)

**Comment by darkdrag00nv2** [comment]
@turbolent @bluesign 

I am getting properties of the `acct` variables as suggestion as expected.

![image](https://github.com/onflow/cadence-tools/assets/122124396/eddced25-68f8-4775-b88a-8de2431b8a81)

I think you have a typo (`acc` instead of `acct`) which is leading to not getting suggestions about `acct`.

**Comment by turbolent** [comment]
Nice! I guess then we can close this issue 👍

**Comment by bluesign** [comment]
Sorry I think I reported this one wrong, now I tried again, I think it is not related to nested context. 

<img width="1049" alt="image" src="https://github.com/onflow/cadence-tools/assets/1119338/734e5352-487a-4b68-a49b-6f69d2190994">

**Comment by darkdrag00nv2** [comment]
I see, it seems like the missing `)` in the end is tripping up the autocompletion. @bluesign Feel free to reopen in that case. I'll take a deeper look.
